# Generated by Django 5.2.14 on 2026-06-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_daily_push',
            field=models.DateField(blank=True, null=True),
        ),
    ]
