# Generated by Django 5.2.14 on 2026-06-05 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_seed_default_tiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daily_push_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
