# Generated by Django 5.2.14 on 2026-06-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_invitation_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tier',
            name='default_sees',
            field=models.CharField(choices=[('own', 'Tasks Only'), ('subproject', 'Sub-Project Only'), ('project', 'Full Project'), ('org', 'Organization')], default='subproject', max_length=12),
        ),
    ]
