# Generated by Django 5.2.10 on 2026-06-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_tier_default_sees'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='enabled_holiday_sets',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
