# Generated by Django 5.2.14 on 2026-06-07 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_daily_push_enabled_user_theme'),
        ('accounts', '0012_organization_enabled_holiday_sets'),
    ]

    operations = [
    ]
