# Generated by Django 5.2.14 on 2026-06-10 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_merge_20260606_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assignment_changes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='deadline_reminders',
            field=models.BooleanField(default=True),
        ),
    ]
