# Generated by Django 5.2.14 on 2026-06-12 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_assignment_changes_user_deadline_reminders'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='state',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
