# Generated by Django 5.2.14 on 2026-06-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_push_hour', models.PositiveSmallIntegerField(default=8)),
                ('daily_push_minute', models.PositiveSmallIntegerField(default=0)),
                ('timezone', models.CharField(default='America/Los_Angeles', max_length=64)),
            ],
            options={
                'verbose_name_plural': 'App settings',
            },
        ),
    ]
