# Generated by Django 5.2.14 on 2026-06-02 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('color', models.CharField(blank=True, max_length=9)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('color', models.CharField(blank=True, max_length=9)),
                ('description', models.TextField(blank=True)),
                ('members_post_without_approval', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subprojects', to='projects.project')),
            ],
            options={
                'ordering': ['project__name', 'name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('project',), name='one_default_subproject_per_project')],
            },
        ),
    ]
