# Generated by Django 5.2.14 on 2026-06-03 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_deleted_at_subproject_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='emoji',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
