# Generated by Django 5.2.14 on 2026-06-05 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_group_name_alter_tier_name_organization_and_more'),
        ('projects', '0003_project_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.organization'),
        ),
    ]
