# Generated by Django 5.2.14 on 2026-06-04 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_tier_user_tier'),
        ('permissions', '0001_initial'),
        ('projects', '0003_project_emoji'),
        ('tasks', '0018_comment_mentions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='accessgrant',
            name='grant_target_exactly_one',
        ),
        migrations.AddField(
            model_name='accessgrant',
            name='sees',
            field=models.CharField(choices=[('own', 'Own tasks only'), ('subproject', 'All tasks in the sub-project'), ('project', 'All tasks in the project')], default='subproject', max_length=12),
        ),
        migrations.AddField(
            model_name='accessgrant',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='accounts.tier'),
        ),
        migrations.AddConstraint(
            model_name='accessgrant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('group__isnull', True), ('tier__isnull', True), ('user__isnull', False)), models.Q(('group__isnull', False), ('tier__isnull', True), ('user__isnull', True)), models.Q(('group__isnull', True), ('tier__isnull', False), ('user__isnull', True)), _connector='OR'), name='grant_target_exactly_one'),
        ),
        migrations.AddField(
            model_name='exclusion',
            name='excluded_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hidden_by', to='accounts.group'),
        ),
        migrations.AddField(
            model_name='exclusion',
            name='excluded_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hidden_by', to='projects.project'),
        ),
        migrations.AddField(
            model_name='exclusion',
            name='excluded_subproject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hidden_by', to='projects.subproject'),
        ),
        migrations.AddField(
            model_name='exclusion',
            name='excluded_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hidden_by', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='exclusion',
            name='excluded_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hidden_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exclusion',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exclusions', to='accounts.group'),
        ),
        migrations.AddField(
            model_name='exclusion',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exclusions', to='accounts.tier'),
        ),
        migrations.AddField(
            model_name='exclusion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exclusions', to=settings.AUTH_USER_MODEL),
        ),
    ]
