# Generated by Django 5.2.14 on 2026-07-20 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_backfill_org_owner'),
        ('permissions', '0004_alter_accessgrant_sees'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_log', to='accounts.organization'),
        ),
    ]
