# Generated by Django 5.2.14 on 2026-06-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_last_daily_push'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assignee_groups',
            field=models.ManyToManyField(blank=True, related_name='assigned_tasks', to='accounts.group'),
        ),
    ]
