# Generated by Django 5.2.14 on 2026-06-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_archived_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=60)),
                ('color', models.CharField(blank=True, max_length=9)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_complete', models.BooleanField(default=False)),
                ('is_initial', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
