# Generated by Django 5.2.14 on 2026-06-03 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_seed_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='monitor',
            field=models.BooleanField(default=False),
        ),
    ]
