# Generated by Django 5.2.14 on 2026-06-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_task_monitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='auto_complete',
            field=models.BooleanField(default=False),
        ),
    ]
