# Generated by Django 5.2.14 on 2026-06-05 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_seed_default_tiers'),
        ('tasks', '0019_recolor_default_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='accounts.organization'),
        ),
    ]
