# Generated by Django 5.2.14 on 2026-06-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_seed_review_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('delayed', 'Delayed'), ('review', 'Ready for Review'), ('done', 'Done')], default='todo', max_length=12),
        ),
        migrations.AlterField(
            model_name='taskoccurrence',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('delayed', 'Delayed'), ('review', 'Ready for Review'), ('done', 'Done')], default='todo', max_length=12),
        ),
    ]
