# Generated by Django 5.2.14 on 2026-06-06 17:12
#
# Subtasks become "mini-tasks": new priority / notes / date-time fields, and the
# single `assignee` FK is replaced by multi-`assignees` + `assignee_groups` M2Ms
# (mirroring Task). The old single assignee is copied into `assignees` BEFORE the
# column is dropped, so no assignment data is lost.

from django.conf import settings
from django.db import migrations, models


def copy_assignee_to_assignees(apps, schema_editor):
    Subtask = apps.get_model('tasks', 'Subtask')
    for sub in Subtask.objects.exclude(assignee__isnull=True):
        sub.assignees.add(sub.assignee_id)


def reverse_copy(apps, schema_editor):
    # Best-effort reverse: keep the first assignee as the single FK.
    Subtask = apps.get_model('tasks', 'Subtask')
    for sub in Subtask.objects.all():
        first = sub.assignees.first()
        if first:
            sub.assignee_id = first.id
            sub.save(update_fields=['assignee'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_organization_enabled_holiday_sets'),
        ('tasks', '0025_rename_review_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. New scalar fields.
        migrations.AddField(
            model_name='subtask',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Lowest'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Highest')], default=3),
        ),
        migrations.AddField(
            model_name='subtask',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subtask',
            name='requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subtask',
            name='timeline_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subtask',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subtask',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subtask',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        # 2. New M2M fields (added while the old FK still exists).
        migrations.AddField(
            model_name='subtask',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='assigned_subtasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subtask',
            name='assignee_groups',
            field=models.ManyToManyField(blank=True, related_name='assigned_subtasks', to='accounts.group'),
        ),
        # 3. Copy the single assignee into the new M2M, then drop the old column.
        migrations.RunPython(copy_assignee_to_assignees, reverse_copy),
        migrations.RemoveField(
            model_name='subtask',
            name='assignee',
        ),
    ]
