# Generated by Django 5.2.14 on 2026-06-07 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_task_deleted_by'),
        ('tasks', '0026_remove_subtask_assignee_subtask_assignee_groups_and_more'),
    ]

    operations = [
    ]
