# Generated by Django 5.2.14 on 2026-06-09 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0027_merge_20260606_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='links',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
