# Generated by Django 5.2.14 on 2026-06-10 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_assignment_changes_user_deadline_reminders'),
        ('tasks', '0029_calendarevent_owner_personalholiday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='personalholiday',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='personalholiday',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_holidays', to=settings.AUTH_USER_MODEL),
        ),
    ]
