# Generated by Django 5.2.14 on 2026-06-29 21:59

import django.db.models.deletion
import sharing.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0017_backfill_org_owner'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, default=sharing.models._gen_token, editable=False, max_length=64, unique=True)),
                ('object_id', models.PositiveIntegerField()),
                ('include_description', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='share_links', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='accounts.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='sharing_sha_content_6d4542_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('content_type', 'object_id'), name='one_active_link_per_object')],
            },
        ),
    ]
