# Generated by Django 5.2.14 on 2026-06-09 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=200)),
                ('locale', models.CharField(db_index=True, max_length=10)),
                ('text', models.TextField()),
                ('approved_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translation_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['locale', 'key'],
                'constraints': [models.UniqueConstraint(fields=('key', 'locale'), name='one_override_per_key_locale')],
            },
        ),
        migrations.CreateModel(
            name='TranslationSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=200)),
                ('locale', models.CharField(db_index=True, max_length=10)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['key'],
                'constraints': [models.UniqueConstraint(fields=('key', 'locale', 'user'), name='one_suggestion_per_key_locale_user')],
            },
        ),
    ]
